package Smarter::Model::RtDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'RtDB::Schema',
    
    
);

=head1 NAME

Smarter::Model::RtDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Smarter>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<RT:::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
